### ISSUE TITLE
[metron.cloud] Can't create an account

### ISSUE THREAD

**Issue by befuddled-dude** [bpepple/metron#126]
I tried to create an account, but never got a verification email. Something went through, because I can't create the account again with the same username.  

Is the verification email broken or is it not active now?

**Comment by bpepple** [comment]
I received an error last night, which I assume is for your account that the e-mail couldn't be delivered to your account. It could be due to your provider blocking e-mail from my MTA.

If you use [Matrix](https://matrix.to/#/#metrondb:matrix.org), you can contact me and I'll manually enable your account (since I don't really want to expose your email/contact info in a bug report).

**Comment by bpepple** [comment]
Fixed.

**Comment by janstieler** [comment]
Hi,
I have the same problem. 
I'm waiting for verification email since last evening.

Cheers

**Comment by bpepple** [comment]
> Hi, I have the same problem. I'm waiting for verification email since last evening.

@janstieler  Have you checked your spam folder? If it's not there send me your e-mail address, and we can manually activate it.

**Comment by janstieler** [comment]
Hi,
I havn't found it in my spam folder, so I would appreciate if you could activate it manually?
My e-mail is **privat@janstieler.de**

Thank you!

Best
Jan

**Comment by bpepple** [comment]
> Hi, I havn't found it in my spam folder, so I would appreciate if you could activate it manually? My e-mail is **[privat@janstieler.de](mailto:privat@janstieler.de)**

There's no record of that e-mail account in our site, perhaps you mistyped it? Regardless, try creating an account again.

**Comment by janstieler** [comment]
Hi,
now I get it to work. I had a JS blocker active which blocked the CAPTCHA so that I can't see that it is missing.
Thanks for your effort!
