### ISSUE TITLE
ComicVine is re-using IDs

### ISSUE THREAD

**Issue by lordwelch** [bpepple/metron#219]
This isn't really a feature request. Just an FYI that ComicVine has been re-using issue IDs and they may not be accurate anymore on metron.cloud
https://discord.com/channels/826493118106697758/826498038885122149/1216482175785111692

**Comment by bpepple** [comment]
Thanks for the heads up, but I don't think this is something we need to worry about too much.

It looks like CV is going back to fix their handling of TPB (which used to be 1TPB -> 1 Series), and deleting some of the series during the consolidation and then reusing the old `cv_id` for new series.

So, this primarily only affects Trade Paperback's Series `cv_id`, and since we've always done TPB as consolidated under 1 series name, we've never added the `cv_id` at the `Series` level, so this shouldn't effect Metron.

**Comment by bpepple** [comment]
Probably should add a validation to the `Series` form to prevent a `cv_id` from being added to a **TPB**.

If Comic Vine finishes merging their TPB's in the future, I can use **Barda** (an internal tool) to add the `cv_id` at a future date.
