### ISSUE TITLE
Add store_date to IssueList schema

### ISSUE THREAD

**Issue by morsok** [bpepple/metron#229]
**Is your feature request related to a problem? Please describe.**
To avoid requesting each issue individually it would be great to have not only the cover date but also the store date on the list of issues

**Describe the solution you'd like**
```diff
{
  "count": 123,
  "next": "http://api.example.org/accounts/?page=4",
  "previous": "http://api.example.org/accounts/?page=2",
  "results": [
    {
      "id": 0,
      "series": {
        "name": "string",
        "volume": 32767,
        "year_began": 32767
      },
      "number": "string",
      "issue": "string",
      "cover_date": "2024-03-29",
+     "store_date": "2024-01-29",
      "image": "string",
      "cover_hash": "string",
      "modified": "2024-03-29T12:55:18.023Z"
    }
  ]
```

**Describe alternatives you've considered**
With the Metron API limit, it would take up to 20 minutes of queued requests to get the store dates on some of those longer runs with like 500 to 600 comics

**Additional context**
When checking out switching Mylar3 to Metron it's one of the main blockers identified so far.

**Comment by bpepple** [comment]
Couple of questions before I implement this:

1. What's the use case for this request?
2. What data are you using from this request?

Seems like a reasonable request, but before adding it I want to make sure the current API doesn't provide a solution for your use-case.

**Comment by evilhero** [comment]
@morsok asked that I chime in, so please accept this as a reponse to your question:

Store date is always preferential to cover date, as store date is the exact date the issue was made available for purchase. Cover date could be anywhere from 1-3 months past the actual store date and as such isn't an accurate indicator of when an issue is released.

1. Mylar uses the store date of an issue when doing matching against a result set, comparing the posting date of a result against the store date to find the most accurate result. Some files contain the month in the filename, so it also uses the date to check for validity in those cases. Using cover date would mean that all the calcs can't be relied on for any consistent accuracy since each publisher has varying degrees to which it extends the cover date past the store date, and sometimes different series from the same publisher have different cover date extensions. 

2. As above, store date being added in the responses means that if using metron, multiple calls to retrieve store date per issue would not be needed and could be gleemed from one api request (generally speaking based on number of issues). Since no filter is available for the issues endpoint,  it currenly can only be done on an individual basis. As an extreme example, having to hit the ``issues`` endpoint for each specific id for a series in order to retrieve the store date value - in the case of a series like 2000AD that becomes a bit excessive. 

Currently only the ``issue/{id}`` endpoint contains the store date value and cannot be found in any other endpoint as far as I'm aware (glancing quickly mind you)

**Comment by bpepple** [comment]
@evilhero Thanks for the quick reply. Mylar's use case is different than most, where the cover date is preferable since it's always there. The API follows the basic layout of [DRF](https://www.django-rest-framework.org/) where the `resource/` endpoint is used to search, and the `resource/id/` is used to get the detail.

Anyway, just wanted to make sure this was actually needed, since it's much **easier** to add a field than to remove it from the API. I should be able to add this sometime this weekend, since it's a non-breaking change.
