### ISSUE TITLE
Filter Issues with Publisher ID and Series ID

### ISSUE THREAD

**Issue by Buried-In-Code** [bpepple/metron#61]
**Is your feature request related to a problem? Please describe.**
You're able to filter the `/issue` endpoint using a Publisher Name and Series Name, but you're unable to filter using the id's returned from the `/publisher` and `/series` endpoints

**Describe the solution you'd like**
Add a filter parameter to `/issue` for Publisher ID and/or Series ID

**Describe alternatives you've considered**
You can work around this by using the rest of the information returned from the `/series` to fill out the params in the `/issue` filter

**Additional context**

**Comment by bpepple** [comment]
Not sure adding a filter for the Series id the `/issue` endpoint is necessary,  since you could use this to get an issue list:

`/api/series/{id}/issue_list/`

Tell me if this works for you.

Now, adding an issuefilter on the Publisher ID is probably worthwhile, and I look at adding it sometime this week when I get some free cycles.

**Comment by Buried-In-Code** [comment]
That helps with getting just a single issue, but as `/api/series/{id}/issue_list` doesn't have any filter options I have to pull each page. but that is an alternative option.
